## Importando librerías

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder, StandardScaler
import tensorflow as tf
from tensorflow.keras import layers, Model
from tensorflow.keras.optimizers.legacy import Adam
from tensorflow.keras.losses import BinaryCrossentropy

## Carga y preprocesado de datos

In [2]:
data = pd.read_csv("Datos/Titanic-Dataset.csv")

In [3]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
def preprocess_dataset(df, categorical_cols, numerical_cols):
    
    titles_dict = {'Capt': 'Other',
               'Major': 'Other',
               'Jonkheer': 'Other',
               'Don': 'Other',
               'Sir': 'Other',
               'Dr': 'Other',
               'Rev': 'Other',
               'Countess': 'Other',
               'Dona': 'Other',
               'Mme': 'Mrs',
               'Mlle': 'Miss',
               'Ms': 'Miss',
               'Mr': 'Mr',
               'Mrs': 'Mrs',
               'Miss': 'Miss',
               'Master': 'Master',
               'Lady': 'Other'}
    
    df['Title'] = df['Name'].str.extract('([A-Za-z]+)\.', expand=False)
    df['Title'] = df['Title'].map(titles_dict) # Creación de la columna 'Title' a partir de los títulos extraídos del nombre
    df['Title'].fillna('Mr', inplace=True)
    means = df.groupby('Title')['Age'].mean().to_dict()
    df.loc[df.Age.isna(),'Age'] = df['Title'].loc[df.Age.isna()].map(means)
    df.Embarked = df.Embarked.fillna('S')
    df["HasCabin"] = df["Cabin"].notna().astype(int) # Creación de la columna 'HasCabin' indicando si el pasajero tenía una cabina asignada
    df['FamilySize'] = df['SibSp'] + df['Parch'] # Creación de la columna 'FamilySize' sumando el número de hermanos/cónyuges y padres/hijos a bordo
    df.drop('SibSp', axis=1, inplace=True)
    df.drop('Parch', axis=1, inplace=True)
    
    # Selección de columnas relevantes para el modelo
    df = df[["Survived",
             "Pclass",
             "Sex",
             "Age",
             "Fare",
             "Embarked",
             "Title",
             "HasCabin",
             "FamilySize"]]
    
    ohe = OneHotEncoder(sparse_output=False)
    scaler = StandardScaler()

    X_num = scaler.fit_transform(df[numerical_cols])
    X_cat = ohe.fit_transform(df[categorical_cols])

    X = np.concatenate([X_num, X_cat], axis=1)
    X = X.astype("float32")

    return ohe, scaler, X

In [5]:
# Categorías numericas y categóricas
numerical_cols = ["Age", 
                  "Fare", 
                  "FamilySize"]

categorical_cols = ["Survived", 
                    "Pclass",
                    "Sex",
                    "Embarked",
                    "Title",
                    "HasCabin"]

In [6]:
ohe, scaler, X = preprocess_dataset(data, categorical_cols=categorical_cols, numerical_cols=numerical_cols)

/var/folders/hc/mb3n8ydj71l7sft8wld706100000gn/T/ipykernel_7235/1122125085.py:23: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Title'].fillna('Mr', inplace=True)

## Parámetros para la GAN

In [7]:
NOISE_DIM = 128
CAT_DIMS = [len(ohe.categories_[i]) for i in range(len(categorical_cols))]
CAT_COLS = sum(CAT_DIMS)
NUM_COLS = len(numerical_cols)
INPUT_DIM = X.shape[1]

In [8]:
# Generador
def build_generator(noise_dim, num_cols, cat_dims):
    input_noise = layers.Input(shape=(noise_dim,)) # Input de ruido aleatorio
    
    x = layers.Dense(64, activation="leaky_relu")(input_noise) # Capa oculta con activación ReLU
    x = layers.BatchNormalization()(x)
    x = layers.Dense(32, activation="leaky_relu")(x) # Segunda capa oculta
    x = layers.BatchNormalization()(x)
    x = layers.Dense(16, activation="leaky_relu")(x) # Tercera capa oculta
    x = layers.BatchNormalization()(x)

    out_num = layers.Dense(num_cols, activation="linear", name="numeric_out")(x) # Salida numérica con activación lineal
    out_cats = []
    for i, dim in enumerate(cat_dims):
        out_cat = layers.Dense(dim, activation="softmax", name=f"cat_out_{i}")(x) # Salida categórica con activación softmax
        out_cats.append(out_cat)
    combined_output = layers.Concatenate()([out_num, *out_cats]) # Combinar salidas numéricas y categóricas
    
    model = Model(inputs=input_noise, outputs=combined_output, name="Generator")
    return model

generator = build_generator(NOISE_DIM, NUM_COLS, CAT_DIMS)

2026-02-18 18:33:10.823270: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M4
2026-02-18 18:33:10.823292: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2026-02-18 18:33:10.823297: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.92 GB
2026-02-18 18:33:10.823317: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2026-02-18 18:33:10.823327: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)

In [9]:
# Discriminador
def build_discriminator(input_dim):
    input_data = layers.Input(shape=(input_dim,)) # Input de datos (reales o generados)
    
    x = layers.Dense(64, activation="leaky_relu")(input_data) # Capa oculta con activación Leaky ReLU
    x = layers.Dropout(0.2)(x)
    x = layers.Dense(32, activation="leaky_relu")(x) # Segunda capa oculta
    x = layers.Dropout(0.2)(x)
    
    output = layers.Dense(1, activation="sigmoid")(x) # Salida de probabilidad con activación sigmoide
    
    model = Model(inputs=input_data, outputs=output, name="Discriminator")
    return model

discriminator = build_discriminator(INPUT_DIM)

In [10]:
# Arquitectura del GAN
class TabularGAN(Model):
    def __init__(self, discriminator, generator, noise_dim):
        super(TabularGAN, self).__init__()
        self.discriminator = discriminator 
        self.generator = generator
        self.noise_dim = noise_dim

    def compile(self, d_optimizer, g_optimizer, loss_fn):
        super(TabularGAN, self).compile()
        self.d_optimizer = d_optimizer
        self.g_optimizer = g_optimizer
        self.loss_fn = loss_fn

    def train_step(self, real_data):
        batch_size = tf.shape(real_data)[0]
        
        # Entrenar el Discriminador
        noise = tf.random.normal(shape=(batch_size, self.noise_dim)) # Generar ruido aleatorio
        fake_data = self.generator(noise) # Generar datos falsos a partir del ruido
        
        # Etiquetas: 1 para real, 0 para falso
        labels_real = tf.ones((batch_size, 1)) * 0.95 # Etiqueta suavizada para reales
        labels_fake = tf.ones((batch_size, 1)) * 0.05 # Etiqueta suavizada para falsos
        labels = tf.concat([labels_real, labels_fake], axis=0) # Combinar etiquetas reales y falsas
        
        with tf.GradientTape() as tape:
            pred_real = self.discriminator(real_data) # Predicciones del discriminador para datos reales
            pred_fake = self.discriminator(fake_data) # Predicciones del discriminador para datos falsos
            pred = tf.concat([pred_real, pred_fake], axis=0) # Combinar predicciones reales y falsas
            
            d_loss = self.loss_fn(labels, pred) # Pérdida del discriminador basada en las etiquetas y predicciones
            
        grads = tape.gradient(d_loss, self.discriminator.trainable_weights)
        self.d_optimizer.apply_gradients(zip(grads, self.discriminator.trainable_weights))

        # Entrenar el Generador
        # Queremos engañar al discriminador, así que etiquetamos los fakes como 1 (real)
        misleading_labels = tf.ones((batch_size, 1))

        with tf.GradientTape() as tape:
            fake_data = self.generator(noise) # Generar datos falsos a partir del mismo ruido
            pred_fake = self.discriminator(fake_data) # Predicciones del discriminador para los datos falsos generados
            g_loss = self.loss_fn(misleading_labels, pred_fake) # Pérdida del generador basada en la capacidad de engañar al discriminador
            
        grads = tape.gradient(g_loss, self.generator.trainable_weights)
        self.g_optimizer.apply_gradients(zip(grads, self.generator.trainable_weights))

        return {"d_loss": d_loss, "g_loss": g_loss}

## Entrenamiento

In [11]:
# Instanciar y compilar
gan = TabularGAN(discriminator=discriminator, generator=generator, noise_dim=NOISE_DIM) # Instancia del GAN con el discriminador, generador y dimensión de ruido
gan.compile(
    d_optimizer=Adam(learning_rate=5e-3),
    g_optimizer=Adam(learning_rate=5e-3),
    loss_fn=BinaryCrossentropy()
)

# Entrenar
gan.fit(X, epochs=200, batch_size=256, verbose=1) 
print("Entrenamiento finalizado.")

Epoch 1/200

2026-02-18 18:33:11.452872: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.

4/4 [==============================] - 1s 117ms/step - d_loss: 0.7012 - g_loss: 0.7245
Epoch 2/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.6462 - g_loss: 0.9146
Epoch 3/200
4/4 [==============================] - 0s 13ms/step - d_loss: 0.5072 - g_loss: 1.4678
Epoch 4/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.5804 - g_loss: 1.1658
Epoch 5/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.7242 - g_loss: 0.9414
Epoch 6/200
4/4 [==============================] - 0s 11ms/step - d_loss: 1.0312 - g_loss: 0.6475
Epoch 7/200
4/4 [==============================] - 0s 10ms/step - d_loss: 1.2360 - g_loss: 0.6415
Epoch 8/200
4/4 [==============================] - 0s 10ms/step - d_loss: 0.6925 - g_loss: 2.5728
Epoch 9/200
4/4 [==============================] - 0s 10ms/step - d_loss: 0.3853 - g_loss: 4.0734
Epoch 10/200
4/4 [==============================] - 0s 10ms/step - d_loss: 0.3596 - g_loss: 2.5826
Epoch 11/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6279 - g_loss: 1.6893
Epoch 12/200
4/4 [==============================] - 0s 13ms/step - d_loss: 1.5846 - g_loss: 0.7053
Epoch 13/200
4/4 [==============================] - 0s 13ms/step - d_loss: 2.4505 - g_loss: 0.2442
Epoch 14/200
4/4 [==============================] - 0s 13ms/step - d_loss: 2.1273 - g_loss: 0.3651
Epoch 15/200
4/4 [==============================] - 0s 13ms/step - d_loss: 1.3097 - g_loss: 1.6697
Epoch 16/200
4/4 [==============================] - 0s 13ms/step - d_loss: 0.9315 - g_loss: 3.0727
Epoch 17/200
4/4 [==============================] - 0s 14ms/step - d_loss: 0.9054 - g_loss: 2.4787
Epoch 18/200
4/4 [==============================] - 0s 14ms/step - d_loss: 1.2481 - g_loss: 1.2797
Epoch 19/200
4/4 [==============================] - 0s 15ms/step - d_loss: 0.7794 - g_loss: 2.1557
Epoch 20/200
4/4 [==============================] - 0s 14ms/step - d_loss: 0.4534 - g_loss: 3.9618
Epoch 21/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.7087 - g_loss: 1.7963
Epoch 22/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.7369 - g_loss: 2.4577
Epoch 23/200
4/4 [==============================] - 0s 13ms/step - d_loss: 0.5573 - g_loss: 3.8093
Epoch 24/200
4/4 [==============================] - 0s 14ms/step - d_loss: 0.6686 - g_loss: 2.3202
Epoch 25/200
4/4 [==============================] - 0s 13ms/step - d_loss: 0.8288 - g_loss: 0.7243
Epoch 26/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.9140 - g_loss: 0.4355
Epoch 27/200
4/4 [==============================] - 0s 13ms/step - d_loss: 0.8792 - g_loss: 0.4436
Epoch 28/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.8210 - g_loss: 0.5074
Epoch 29/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.7572 - g_loss: 0.6093
Epoch 30/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6980 - g_loss: 0.7332
Epoch 31/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6619 - g_loss: 0.8826
Epoch 32/200
4/4 [==============================] - 0s 10ms/step - d_loss: 0.6285 - g_loss: 1.0161
Epoch 33/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6201 - g_loss: 1.0599
Epoch 34/200
4/4 [==============================] - 0s 10ms/step - d_loss: 0.6299 - g_loss: 0.9891
Epoch 35/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6646 - g_loss: 0.8567
Epoch 36/200
4/4 [==============================] - 0s 10ms/step - d_loss: 0.6997 - g_loss: 0.7656
Epoch 37/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.7142 - g_loss: 0.7475
Epoch 38/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.7195 - g_loss: 0.7624
Epoch 39/200
4/4 [==============================] - 0s 14ms/step - d_loss: 0.7150 - g_loss: 0.7760
Epoch 40/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.6929 - g_loss: 0.7819
Epoch 41/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.6690 - g_loss: 0.7979
Epoch 42/200
4/4 [==============================] - 0s 10ms/step - d_loss: 0.6440 - g_loss: 0.8447
Epoch 43/200
4/4 [==============================] - 0s 13ms/step - d_loss: 0.6083 - g_loss: 0.9226
Epoch 44/200
4/4 [==============================] - 0s 13ms/step - d_loss: 0.5753 - g_loss: 1.0006
Epoch 45/200
4/4 [==============================] - 0s 13ms/step - d_loss: 0.5578 - g_loss: 1.0206
Epoch 46/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.5664 - g_loss: 0.9678
Epoch 47/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.5878 - g_loss: 0.8643
Epoch 48/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6360 - g_loss: 0.7625
Epoch 49/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6858 - g_loss: 0.6920
Epoch 50/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.7359 - g_loss: 0.6456
Epoch 51/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.7726 - g_loss: 0.6129
Epoch 52/200
4/4 [==============================] - 0s 10ms/step - d_loss: 0.7939 - g_loss: 0.5901
Epoch 53/200
4/4 [==============================] - 0s 10ms/step - d_loss: 0.7908 - g_loss: 0.5870
Epoch 54/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.7452 - g_loss: 0.6279
Epoch 55/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.7008 - g_loss: 0.7251
Epoch 56/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6453 - g_loss: 0.8332
Epoch 57/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6186 - g_loss: 0.8803
Epoch 58/200
4/4 [==============================] - 0s 13ms/step - d_loss: 0.6321 - g_loss: 0.8425
Epoch 59/200
4/4 [==============================] - 0s 13ms/step - d_loss: 0.6869 - g_loss: 0.7396
Epoch 60/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.7405 - g_loss: 0.6522
Epoch 61/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.7417 - g_loss: 0.6656
Epoch 62/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.7228 - g_loss: 0.7026
Epoch 63/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.7096 - g_loss: 0.6930
Epoch 64/200
4/4 [==============================] - 0s 13ms/step - d_loss: 0.6831 - g_loss: 0.7092
Epoch 65/200
4/4 [==============================] - 0s 13ms/step - d_loss: 0.6674 - g_loss: 0.7412
Epoch 66/200
4/4 [==============================] - 0s 13ms/step - d_loss: 0.6597 - g_loss: 0.7601
Epoch 67/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.6572 - g_loss: 0.7585
Epoch 68/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6765 - g_loss: 0.7396
Epoch 69/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6934 - g_loss: 0.7177
Epoch 70/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.7093 - g_loss: 0.7087
Epoch 71/200
4/4 [==============================] - 0s 17ms/step - d_loss: 0.7208 - g_loss: 0.7234
Epoch 72/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.7192 - g_loss: 0.7615
Epoch 73/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.7115 - g_loss: 0.8046
Epoch 74/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6992 - g_loss: 0.8346
Epoch 75/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6884 - g_loss: 0.8475
Epoch 76/200
4/4 [==============================] - 0s 13ms/step - d_loss: 0.6867 - g_loss: 0.8458
Epoch 77/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.6900 - g_loss: 0.8267
Epoch 78/200
4/4 [==============================] - 0s 13ms/step - d_loss: 0.7070 - g_loss: 0.8010
Epoch 79/200
4/4 [==============================] - 0s 13ms/step - d_loss: 0.7160 - g_loss: 0.7909
Epoch 80/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.7187 - g_loss: 0.8141
Epoch 81/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.7148 - g_loss: 0.8140
Epoch 82/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.7253 - g_loss: 0.7973
Epoch 83/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.7141 - g_loss: 0.7866
Epoch 84/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.7078 - g_loss: 0.7747
Epoch 85/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.7087 - g_loss: 0.7566
Epoch 86/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.7070 - g_loss: 0.7369
Epoch 87/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.7008 - g_loss: 0.7354
Epoch 88/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.7002 - g_loss: 0.7550
Epoch 89/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6814 - g_loss: 0.7656
Epoch 90/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6836 - g_loss: 0.7524
Epoch 91/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6939 - g_loss: 0.7220
Epoch 92/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.7106 - g_loss: 0.6895
Epoch 93/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.7231 - g_loss: 0.6651
Epoch 94/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.7329 - g_loss: 0.6535
Epoch 95/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.7295 - g_loss: 0.6505
Epoch 96/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.7290 - g_loss: 0.6452
Epoch 97/200
4/4 [==============================] - 0s 13ms/step - d_loss: 0.7242 - g_loss: 0.6370
Epoch 98/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.7193 - g_loss: 0.6317
Epoch 99/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.7018 - g_loss: 0.6343
Epoch 100/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6877 - g_loss: 0.6473
Epoch 101/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6661 - g_loss: 0.6678
Epoch 102/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6474 - g_loss: 0.6923
Epoch 103/200
4/4 [==============================] - 0s 10ms/step - d_loss: 0.6355 - g_loss: 0.7186
Epoch 104/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6202 - g_loss: 0.7442
Epoch 105/200
4/4 [==============================] - 0s 10ms/step - d_loss: 0.6051 - g_loss: 0.7686
Epoch 106/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.5936 - g_loss: 0.7948
Epoch 107/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.5785 - g_loss: 0.8216
Epoch 108/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.5644 - g_loss: 0.8456
Epoch 109/200
4/4 [==============================] - 0s 13ms/step - d_loss: 0.5595 - g_loss: 0.8584
Epoch 110/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.5629 - g_loss: 0.8492
Epoch 111/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.5883 - g_loss: 0.8088
Epoch 112/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6265 - g_loss: 0.7500
Epoch 113/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6446 - g_loss: 0.7331
Epoch 114/200
4/4 [==============================] - 0s 10ms/step - d_loss: 0.6270 - g_loss: 0.8058
Epoch 115/200
4/4 [==============================] - 0s 10ms/step - d_loss: 0.5960 - g_loss: 0.9051
Epoch 116/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.5845 - g_loss: 0.9038
Epoch 117/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6143 - g_loss: 0.7963
Epoch 118/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6264 - g_loss: 0.7835
Epoch 119/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6110 - g_loss: 0.9072
Epoch 120/200
4/4 [==============================] - 0s 10ms/step - d_loss: 0.5815 - g_loss: 1.0277
Epoch 121/200
4/4 [==============================] - 0s 10ms/step - d_loss: 0.5482 - g_loss: 1.0917
Epoch 122/200
4/4 [==============================] - 0s 10ms/step - d_loss: 0.5354 - g_loss: 1.0669
Epoch 123/200
4/4 [==============================] - 0s 13ms/step - d_loss: 0.5556 - g_loss: 0.9847
Epoch 124/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.5940 - g_loss: 0.9706
Epoch 125/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.5999 - g_loss: 1.0195
Epoch 126/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.5690 - g_loss: 1.0481
Epoch 127/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.5630 - g_loss: 1.0569
Epoch 128/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6100 - g_loss: 0.9570
Epoch 129/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6451 - g_loss: 0.8639
Epoch 130/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6534 - g_loss: 0.9518
Epoch 131/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6612 - g_loss: 1.1358
Epoch 132/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6331 - g_loss: 1.1205
Epoch 133/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6292 - g_loss: 0.9327
Epoch 134/200
4/4 [==============================] - 0s 10ms/step - d_loss: 0.6441 - g_loss: 0.8670
Epoch 135/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6002 - g_loss: 1.1114
Epoch 136/200
4/4 [==============================] - 0s 10ms/step - d_loss: 0.5797 - g_loss: 1.2846
Epoch 137/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6045 - g_loss: 1.1583
Epoch 138/200
4/4 [==============================] - 0s 10ms/step - d_loss: 0.6637 - g_loss: 0.9140
Epoch 139/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6860 - g_loss: 0.8696
Epoch 140/200
4/4 [==============================] - 0s 10ms/step - d_loss: 0.6517 - g_loss: 1.1064
Epoch 141/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.5534 - g_loss: 1.4392
Epoch 142/200
4/4 [==============================] - 0s 10ms/step - d_loss: 0.4812 - g_loss: 1.4924
Epoch 143/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.5353 - g_loss: 1.0009
Epoch 144/200
4/4 [==============================] - 0s 17ms/step - d_loss: 0.5801 - g_loss: 0.9607
Epoch 145/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.6166 - g_loss: 1.1591
Epoch 146/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.7207 - g_loss: 1.0461
Epoch 147/200
4/4 [==============================] - 0s 13ms/step - d_loss: 0.7565 - g_loss: 0.8635
Epoch 148/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.7347 - g_loss: 0.7940
Epoch 149/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.7237 - g_loss: 0.7637
Epoch 150/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6920 - g_loss: 0.7268
Epoch 151/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6381 - g_loss: 0.7416
Epoch 152/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.5887 - g_loss: 0.8220
Epoch 153/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.5603 - g_loss: 0.8889
Epoch 154/200
4/4 [==============================] - 0s 10ms/step - d_loss: 0.5439 - g_loss: 0.9385
Epoch 155/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.5430 - g_loss: 0.9577
Epoch 156/200
4/4 [==============================] - 0s 10ms/step - d_loss: 0.5615 - g_loss: 0.9203
Epoch 157/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.5285 - g_loss: 1.0446
Epoch 158/200
4/4 [==============================] - 0s 13ms/step - d_loss: 0.4965 - g_loss: 1.2322
Epoch 159/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.4776 - g_loss: 1.2854
Epoch 160/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.4550 - g_loss: 1.2504
Epoch 161/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.4642 - g_loss: 1.1388
Epoch 162/200
4/4 [==============================] - 0s 10ms/step - d_loss: 0.5461 - g_loss: 1.0966
Epoch 163/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6272 - g_loss: 1.1861
Epoch 164/200
4/4 [==============================] - 0s 10ms/step - d_loss: 0.6455 - g_loss: 1.1623
Epoch 165/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6295 - g_loss: 1.1064
Epoch 166/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.5934 - g_loss: 1.1237
Epoch 167/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6314 - g_loss: 1.1078
Epoch 168/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6497 - g_loss: 1.0981
Epoch 169/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.5786 - g_loss: 1.2884
Epoch 170/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.5607 - g_loss: 1.3407
Epoch 171/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6929 - g_loss: 1.0670
Epoch 172/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.7794 - g_loss: 1.2145
Epoch 173/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.7027 - g_loss: 1.8391
Epoch 174/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.7113 - g_loss: 1.4883
Epoch 175/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.6927 - g_loss: 1.1077
Epoch 176/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.7120 - g_loss: 0.7073
Epoch 177/200
4/4 [==============================] - 0s 13ms/step - d_loss: 0.7209 - g_loss: 0.5726
Epoch 178/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.6738 - g_loss: 0.6609
Epoch 179/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.6377 - g_loss: 0.8251
Epoch 180/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.6420 - g_loss: 0.8683
Epoch 181/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.7268 - g_loss: 0.7448
Epoch 182/200
4/4 [==============================] - 0s 12ms/step - d_loss: 0.7701 - g_loss: 0.7175
Epoch 183/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.7874 - g_loss: 0.8560
Epoch 184/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.7770 - g_loss: 0.9982
Epoch 185/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.7317 - g_loss: 1.0116
Epoch 186/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6700 - g_loss: 0.9575
Epoch 187/200
4/4 [==============================] - 0s 10ms/step - d_loss: 0.6212 - g_loss: 0.8950
Epoch 188/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.5985 - g_loss: 0.8892
Epoch 189/200
4/4 [==============================] - 0s 10ms/step - d_loss: 0.5862 - g_loss: 0.9792
Epoch 190/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.5682 - g_loss: 1.0183
Epoch 191/200
4/4 [==============================] - 0s 10ms/step - d_loss: 0.5782 - g_loss: 0.8940
Epoch 192/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6264 - g_loss: 0.7625
Epoch 193/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6325 - g_loss: 0.7504
Epoch 194/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.6005 - g_loss: 0.8234
Epoch 195/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.5729 - g_loss: 0.8293
Epoch 196/200
4/4 [==============================] - 0s 10ms/step - d_loss: 0.5540 - g_loss: 0.8057
Epoch 197/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.5510 - g_loss: 0.8219
Epoch 198/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.5444 - g_loss: 0.8860
Epoch 199/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.5376 - g_loss: 1.0248
Epoch 200/200
4/4 [==============================] - 0s 11ms/step - d_loss: 0.5313 - g_loss: 1.1020
Entrenamiento finalizado.

## Generación de datos sintéticos

In [12]:

def generate_synthetic_data(num):
    # Generar datos sintéticos brutos
    noise = tf.random.normal(shape=(num, NOISE_DIM))
    generated_raw = generator.predict(noise)

    # Separar numéricos y categóricos
    gen_num_scaled = generated_raw[:, :NUM_COLS]
    gen_cat_probs = generated_raw[:, NUM_COLS:]

    # Revertir escalado numérico
    gen_num = scaler.inverse_transform(gen_num_scaled)

    gen_cat = [[] for _ in range(num)]

    # Convertir probabilidades categóricas a índices y luego a categorías originales
    for i, dim in enumerate(CAT_DIMS):
        start_idx = sum(CAT_DIMS[:i])
        end_idx = start_idx + dim
        cat_probs = gen_cat_probs[:, start_idx:end_idx]
        cat_indices = np.argmax(cat_probs, axis=1)
        for i, idx in enumerate(cat_indices):
            aux = [0 for _ in range(dim)]
            aux[idx] = 1
            gen_cat[i] += aux
    
    gen_cat = ohe.inverse_transform(gen_cat)

    # Concatenar numéricos y categóricos para obtener el dataset sintético completo
    generated_data = np.concatenate([gen_num, gen_cat], axis=1)
    
    return generated_data

pd.DataFrame(generate_synthetic_data(10), columns = numerical_cols + categorical_cols).head(10)

1/1 [==============================] - 0s 102ms/step

,Age,Fare,FamilySize,Survived,Pclass,Sex,Embarked,Title,HasCabin
0,11.715076,53.226341,0.933232,0,3,male,S,Mr,0
1,32.859222,34.851578,0.618968,0,3,male,S,Mr,0
2,12.598082,54.511597,0.965544,0,3,male,S,Mr,0
3,33.86256,38.070343,0.861374,0,3,male,S,Mr,0
4,33.544601,87.001999,1.059978,0,1,male,S,Mr,1
5,31.438448,36.264442,0.673428,0,3,male,S,Mr,0
6,29.377378,44.085743,0.847661,0,3,male,S,Mr,0
7,19.334831,55.170666,1.200937,0,3,male,S,Mr,0
8,5.874833,61.81665,1.43644,0,3,male,S,Mr,0
9,33.426453,49.221439,0.678579,0,3,male,S,Mr,0

Los datos generados parecen bastante decentes en su mayoría, sin embargo, se están generando datos ilógicos para ciertas escalas númericas, además parece haber una tendencia a la repetición de datos categóricos. Nuestro generador podría ser mejor tal vez con un enfoque distinto en la arquitectura o en las funciones de activación.